name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout winsparkle
        uses: actions/checkout@v4
        with:
          repository: vslavik/winsparkle
          ref: refs/tags/v0.8.3
          path: .

      - name: Fetch deps
        run: |
          git submodule update --init --recursive

      - name: Restore dependency packages
        run: |
          nuget restore

      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.29
          sdk: 10.0.19041.0

      - name: Build
        run: msbuild WinSparkle.sln
          /p:PlatformToolset=v142 `
          /p:Platform=x64 `
          /p:Configuration=Release `
          /p:WholeProgramOptimization=true `
          /p:Optimization=MinSpace `
          /p:FunctionLevelLinking=true

      - name: Archive Binary
        uses: actions/upload-artifact@v4
        with:
          name: winsparkle
          path: |
            x64/Release/*.dll
